# pubspec.yaml
name: my_ddd_app
description: DDD based Flutter application
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Functional Programming
  fpdart: ^1.1.0

  # Data Classes

  # Navigation
  go_router: ^16.1.0

  # Dependency Injection
  injectable: ^2.3.0
  get_it: ^7.6.0

  # Network
  dio: ^5.4.0
  retrofit: ^4.0.0

  # Local Storage
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0

  # Firebase (Optional)
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.0
  firebase_analytics: ^10.8.0

  # Utils
  uuid: ^4.2.0
  logger: ^2.0.0
  intl: ^0.18.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  supabase_flutter: ^2.9.1
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.3
  my_ddd_app_lints:
    path: tools/analyzer_plugin
  flutter_test:
    sdk: flutter

  # Code Generation

  # Testing
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4
